import { GoogleSpreadsheet } from 'google-spreadsheet';
import * as dotenv from 'dotenv';

dotenv.config();

// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet(process.env.SHEET_ID);

(async () => {
  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    // eslint-disable-next-line @typescript-eslint/naming-convention
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL ?? '',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    private_key: (process.env.GOOGLE_PRIVATE_KEY ?? '').replace(/\\n/g, '\n'),
  });

  await doc.loadInfo(); // loads document properties and worksheets
  console.log(doc.title);
})();
