# プルリクにラベルを付ける
# https://dev.classmethod.jp/articles/github-actions-pull-request-labeler/
# https://github.com/actions/labeler
name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
